import { type NextPage } from "next";
import Head from "next/head";
import { api } from "../utils/api";
import { useState } from "react";
import Link from "next/link";

const Home: NextPage = () => {
  const [input, setInput] = useState<string>("");
  const getUrls = api.url.getAllUrl.useQuery();

  const getShortUrl = api.url.shortenUrl.useMutation({
    onSuccess: (data) => {
      console.log("Successfully saved in db!");
      console.log(data);
    },
    onError: (err) => {
      console.error("failed: ", err);
    },
  });

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    getShortUrl.mutate({ longUrl: input });
  };

  return (
    <>
      <Head>
        <title>Tiny URL Shortener clone</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex h-screen w-full items-center justify-center bg-slate-800">
        <div>
          <form onSubmit={handleSubmit}>
            <label
              htmlFor="longUrl"
              className="mb-3 block text-3xl font-semibold text-slate-300"
            >
              Enter Long URL
            </label>
            <input
              type="text"
              name="longUrl"
              id="longUrl"
              className="w-96 rounded p-2 text-lg outline-none"
              value={input}
              onChange={(e) => setInput(e.target.value)}
            />
            <button
              type="submit"
              className="ml-2 rounded bg-blue-800 py-2 px-5 text-lg text-white hover:bg-blue-900"
            >
              make it short
            </button>
          </form>

          <div className="flex flex-col">
            <h2 className="my-5 text-2xl font-semibold text-slate-500">
              Here is the list of short URLs
            </h2>
            <div>
              <table className="w-full bg-transparent shadow-lg">
                <thead>
                  <tr className="border bg-slate-700 px-8 py-4 text-left text-lg text-slate-300">
                    <th className="border px-8 py-4">Long URL</th>
                    <th className="border px-8 py-4">Short URL</th>
                  </tr>
                </thead>
                <tbody>
                  {getUrls.data?.map(({ longUrl, shortUrl, id }) => (
                    <tr key={id}>
                      <td className="border px-8 py-4 text-white">{longUrl}</td>
                      <td className="border px-8 py-4 text-white">
                        <Link href={`/${shortUrl}`}>{shortUrl}</Link>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
